### PR TITLE
Replace supervisord with S6

### PR DESCRIPTION
**Pull request by cboettig**
S6 offers a much nicer solution to the pid reaping problem in supervisord (which also appeared in runit).  See a detailed overview of S6 here: http://skarnet.org/software/s6/why.html

In particular, it handles the issue of wanting to run some configuration scripts (e.g. to create the appropriate user and permissions) before starting the service (rstudio) explicitly and elegantly.  It supports a cleaner start and stop process, and is lighter and faster than supervisord and more intuitive than runit.  

RStudio container logs should be cleaner now as well (supervisord insists in logging things that look like errors even though they are not).  

This just uses the Docker overlay approach to set up S6: https://github.com/just-containers/s6-overlay .

I've been testing this on the rstudio-daily image for the past week; so far so good.  I'll leave this PR pending for a few days for comments before merging.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Shall we merge, or this Travis FAIL an issue.

**Comment by cboettig** [comment]
ha! Touche.  Actually the travis fails appear to be on building  r-base, nor sure why.  Will kick travis in a few hours and see if it straightens up.

**Comment by cboettig** [comment]
Okay, think this is ready to merge when you are ready.  As suspected, just travis being silly before (and then I forgot about this).

**Comment by eddelbuettel** [comment]
I take your word for it :)

**Pull request merged**
