### PR TITLE
Add BLAS Build Handling

### PR DESCRIPTION
**Pull request by jlisic**
BLAS build handling added to improve performance, currently only the libre OpenBLAS and ATLAS are included.  Also added some comments to the Dockerfile.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Hm.

We generally prefer discussion before unsolicited PRs.  I am not so sure how I feel about this one.

**Comment by jlisic** [comment]
Hi Dirk,
 
Sorry, I'm a bit new to contributing on GitHub, so I'm not entirely up-to-date with GitHub etiquette.  I'll be happy to either close or delete the pull request.  

Thanks, 

Jonathan

**Comment by eddelbuettel** [comment]
We can discuss now.  Usually @cboettig and I prefer to steer requests that are "too specific" back to the requester.   I have the feeling that if you really truly need it maybe you should just make the change locally.   We generally prefer to err on the side of distro defaults and avoid all possible permutation.

**Comment by eddelbuettel** [comment]
And in all fairness you had opened #254 but I am not sure we arrived at anything actionable yet...

**Comment by jlisic** [comment]
No problem, I just thought I'd share some changes that I found useful.  Perhaps it might be worth adding a note on the readme that R-ver uses openblas, therefore more preferable for BLAS intensive workloads.  While, R-base uses native R BLAS, useful for testing and less BLAS intensive workloads.

I also have a full set of centos 6 and 7 variant of R-ver and R-base if you are interested :smiley:.

**Comment by eddelbuettel** [comment]
I like that. It can definitely go into the wiki, methinks.

**Pull request closed without merging**
