### PR TITLE
Update tables to reflect current stacks

### PR DESCRIPTION
**Pull request by cboettig**
Link to the current image files, add download metrics, use the detect "automated build" shield for build status

### CODE REVIEW

**Comment by cboettig** [comment]
@eddelbuettel Have you had a chance to take a quick look at this?  Just some updated links and a bit more info for the tables in the README

**Comment by eddelbuettel** [comment]
Yes sir I did and appreciate this -- I didn't see it rendered though.  Is is somewhere?  Else I just approve / merge and we pick up the pieces afterwards.

**Comment by cboettig** [comment]
You can use the "rich diff" button to see it rendered before merging: https://github.com/rocker-org/rocker/pull/242/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by eddelbuettel** [comment]
Good point.  Because they render markdown and tables 'as is'.

**Pull request merged**
