### PR TITLE
add opensuse-based r-bspm images

### PR DESCRIPTION
**Pull request by Enchufa2**
And the same as #444, but for our openSUSE friends. Funny enough, `-n` means for zypper the same as `-y` for the rest of the world. We can tag these `r-bspm:leap` and ~`r-bspm:dumbledore`~ `r-bspm:tumbleweed`.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Do we need two? Or is one good enough?  Apart from Detlef I don't really know anybody using OpenSuSE.

**Comment by Enchufa2** [comment]
Fine with me. Let's keep Tumbleweed then? Leap has some annoyingly old package versions (e.g., R 3.5.0 by default, unless you add another repo).

**Comment by eddelbuettel** [comment]
Perfect. Thanks for adding it.  I'll set up a build at the Docker Hub in due course.

**Comment by eddelbuettel** [comment]
Turns out the build at Docker Hub failed over a glibc / seccomp issue that I was able to overcome with the current Docker binary so an image has been pushed.

**Pull request merged**
