### PR TITLE
Updated libssl to 1.0.2

### PR DESCRIPTION
**Pull request by b-sam**
The Dockerfile doesn't compile anymore because the package libssl1.0.0 is not found.
Changed the package to libssl1.0.2

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Actually, `libssl-dev` (which is the next line) depends on this (ie `libssl1.0.2`) so this is somewhat redundant.

In other words instead of changing from `libssl1.0.0` to `libssl1.0.2` we can probably just delete the line.

**Comment by b-sam** [comment]
Actually, rstudio-server doesn't like libssl1.0.2, so I ended up using the libssl1.0.0 from the debian stable branch.
It's not clean but here is what I ended up using.

`RUN sh -c "echo 'deb http://ftp.de.debian.org/debian jessie main' >> /etc/apt/sources.list"

RUN rm -rf /var/lib/apt/lists/ \
  && apt-get update \
  && apt-get install -t stable libssl1.0.0 \
  && apt-get install -y  --no-install-recommends \
    ca-certificates \
    file \
    git \
    libapparmor1 \
    libedit2 \
    libcurl4-openssl-dev \
    libssl-dev \
    psmisc \
    python-setuptools \
    sudo \
  && VER=$(wget --no-check-certificate -qO- https://s3.amazonaws.com/rstudio-server/current.ver) \
  && wget -q http://download2.rstudio.org/rstudio-server-${VER}-amd64.deb \
  && dpkg -i rstudio-server-${VER}-amd64.deb \
  && rm rstudio-server-*-amd64.deb \
  && ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc /usr/local/bin \
  && ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc /usr/local/bin \
  && wget https://github.com/jgm/pandoc-templates/archive/1.15.0.6.tar.gz \
  && mkdir -p /opt/pandoc/templates && tar zxf 1.15.0.6.tar.gz \
  && cp -r pandoc-templates*/* /opt/pandoc/templates && rm -rf pandoc-templates* \
  && mkdir /root/.pandoc && ln -s /opt/pandoc/templates /root/.pandoc/templates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/
`

**Comment by eddelbuettel** [comment]
I am not sure what your issue is.  Even the simpler `rocker` image at the base of it all already has `libssl1.0.2` installed:

edd@box:/tmp$ docker run --rm -ti r-base /bin/bash
root@ee313d4a538b:/# dpkg -s libssl1.0.2
Package: libssl1.0.2
Status: install ok installed
Priority: important
Section: libs
Installed-Size: 3521
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: same
Source: openssl
Version: 1.0.2h-1
Depends: libc6 (>= 2.14), debconf (>= 0.5) | debconf-2.0
Description: Secure Sockets Layer toolkit - shared libraries
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It provides the libssl and libcrypto shared libraries.
root@ee313d4a538b:/# 
```

**Comment by b-sam** [comment]
Rstudio server needs libssl1.0.0 to start. Couldn't have it start without it.

**Comment by eddelbuettel** [comment]
Oh, right -- forgot about that.

**Comment by cboettig** [comment]
LGTM.  Thanks for the PR.  

Guess we need a new strategy for travis since the r-dev image takes too long for travis to build now it seems.

**Comment by eddelbuettel** [comment]
No it is not a time out but a regular build failure.  Not sure why ...

See eg https://travis-ci.org/rocker-org/rocker/builds/145717352

**Comment by cboettig** [comment]
huh, weird. guess I cannot read long travis logs on my phone well.  will take a look on a local build

**Comment by eddelbuettel** [comment]
I did tickle drd the other and should look at r-devel too.   May turn them back on but maybe at a weekly cadence.  Daily is just too much ...

**Comment by cboettig** [comment]
agreed. sounds like a plan.

**Comment by eddelbuettel** [comment]
Unsurprisingly, it bombed for me (locally) the same way Travis and Circle bombed.  I'll run it 'by hand' in a Debian testing container to see which sub-component in the (large-ish) compund `CMD ...` fails.

**Comment by eddelbuettel** [comment]
Hm. It is part of the make step:

```bash
make[1]: Entering directory '/tmp/R-devel/doc'
/bin/bash: line 2: ../bin/R: No such file or directory
make[1]: *** [NEWS.rds] Error 127
Makefile:48: recipe for target 'NEWS.rds' failed
make[1]: Leaving directory '/tmp/R-devel/doc'
make: *** [R] Error 1
Makefile:60: recipe for target 'R' failed
```

That seems flaky but part of R.  Maybe `make -k` is the answer...

**Comment by eddelbuettel** [comment]
It is an R bug.  `make` descends into `doc/` before `src/` to `R` may not exist yet.  I'll email r-devel.

**Comment by eddelbuettel** [comment]
I reported it on r-devel and it has now been fixed.  The `make doc` subdir target accidentally dependent on R itself, this has been reverted.  Running a happy test build now, will tickle r-devel on the hub too.

**Comment by cboettig** [comment]
Nice work!

**Pull request merged**
