### PR TITLE
add fedora-based r-bspm images

### PR DESCRIPTION
**Pull request by Enchufa2**
For Fedora 33 (current stable release) and rawhide, under the `r-bspm` directory, as discussed. I tried to follow the other images' _philosophy_ (docker user, availability of `install.r` and `remotes`).

### CODE REVIEW

**Comment by eddelbuettel** [comment]
It adds another layer to the directory structure.  Currently we just have `r-bspm/${FLAVOUR}/Dockerfile`. And I like that better.

Maybe `fc33` and `fcrawhide` or something?

**Comment by Enchufa2** [comment]
Apologies, it still requires an adjustment.

**Comment by eddelbuettel** [comment]
What was the change?  They look good to me...  (and we simply could add one or more softlinks -- `install2.r`, originally written by @cboettig for our use in Dockerfiles, it pretty handy too -- but `install.r` will do for demo purposes).   Nice and tidy.

Does this need the 'work in progress' tag?

**Comment by Enchufa2** [comment]
Ready now. I forgot to set `repos` for the fallback and the path to the user's library was wrong.

**Review by eddelbuettel — APPROVED** [review]

**Comment by eddelbuettel** [comment]
What's a better / more common tag for the container then?  'fc33' ? 'f33' ? '33' ?

**Comment by Enchufa2** [comment]
Better f33.

**Comment by eddelbuettel** [comment]
Will do.

**Comment by eddelbuettel** [comment]
They are there now:  https://hub.docker.com/r/rocker/r-bspm/tags?page=1&ordering=last_updated

**Comment by Enchufa2** [comment]
Great, thanks!

**Pull request merged**
