### PR TITLE
candidate Dockerfiles

### PR DESCRIPTION
**Pull request by eddelbuettel**
Following earlier discussion, I just cobbled this together and tested locally.   Open questions:

- good idea?
- naming / directory layout?
- here or outside of Docker?

It works nicely:

```
edd@max:~$ docker run --rm -ti rocker:r-precise-apt apt-cache search r-cran- | wc -l
2748
edd@max:~$ docker run --rm -ti rocker:r-trusty-apt apt-cache search r-cran- | wc -l
2817
edd@max:~$ 
```

### CODE REVIEW

**Comment by cboettig** [comment]
> -  good idea

yup, looks useful to me.  Particularly given the current situation with the armstrong deb repos, having these images with the marutter repo would be handy.

- naming / directory layout

Reasonable given the use case.  Would the Docker image on the hub be named `rocker/r-apt-cache:trusty`, etc, (subdirectory as image name, following the convention of the repo, and then maybe base version as tag), or is that too verbose?   If we do distro-release as tags, maybe just at 'latest' tag that points to 'ubuntu' would also be sensible.

I also wonder if r-apt-cache is too jargony?  Can't think of something concise that better communicates the idea though.  

- here is fine with me.  Most people tend to use the rocker/ repo to file issues etc, even if they are really hadleyverse issues, so it's seems to make little difference where we put them.  


Do you think it's confusing to have rocker images don't have r-base already installed?

**Comment by eddelbuettel** [comment]
"size":  Not using r-base is an option too.  I was foolishly thinking that the R interface offered by RcppAPT could be a next step. It doesn't do all that much (yet ?).   OTOH these aren't exactly minimal either because software-properties-common pulls in a ton of stuff.   We could go leaner and meander.

"naming":  Yes, I like the distro as a tag.  As a test I did 

```
edd@max:~$ docker images | head -3
REPOSITORY                   TAG                   IMAGE ID            CREATED             VIRTUAL SIZE
rocker                       r-precise-apt         f51f65b03db4        16 hours ago        218.2 MB
rocker                       r-trusty-apt          99bbbd86f817        17 hours ago        247.5 MB
edd@max:~$ 
```

and I am still completely open on names of the directories, associated hub names, etc pp.

**Comment by eddelbuettel** [comment]
Actually, another reason R in there is probably that we want `available.packages()` too to compare the two sides.

**Comment by cboettig** [comment]
yup, all sounds good to me

**Comment by eddelbuettel** [comment]
Kewl. That was helpful.  I'll do another iteration one of these days.

**Comment by eddelbuettel** [comment]
> I also wonder if r-apt-cache is too jargony?

How about `r-apt:{trusty,vivid}` ?

**Comment by cboettig** [comment]
Sure

On Tue, Dec 22, 2015, 5:08 PM Dirk Eddelbuettel <notifications@github.com>
wrote:

> I also wonder if r-apt-cache is too jargony?
>
> How about r-apt:{trusty,vivid} ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rocker-org/rocker/pull/157#issuecomment-166771929>.
>
-- 

http://carlboettiger.info

**Comment by eddelbuettel** [comment]
I renamed and extended as discussed. I think this can be merged now (and I'd be happy to do so in a day or two) in order to have it built.

**Pull request merged**
